### ISSUE TITLE
Use of Non Global API

### ISSUE THREAD

**Issue by WhyAydan** [deadbeef3137/ha-cloudflare-tunnel-monitor#1]
Hello,

Awesome work on this integration by the way!

However is there any chance that we don't need to use the Global API key? Not to happy security wise to be using the Global API.

Aydan

**Comment by deadbeef3137** [comment]
Hello @WhyAydan,

Thank you very much for your feedback. The truth is that I made it using the global API because I already knew how to work with it, and I was able to integrate it very quickly. Since I did it out of necessity and it was quite urgent at the time, I chose this approach.

Currently, I don't have much time, but in the near future, I would like to use API tokens instead of the global API if possible.

Best regards.

**Comment by syphernl** [comment]
PR #6 will make it possible to use it with a non global API key. Tested and it works fine on my install with a non-global API key.

**Comment by WhyAydan** [comment]
Confirmed working on my setup as well :)

**Comment by deadbeef3137** [comment]
Thank you very much @syphernl.
Amazing work.
